spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/fx
    username: user
    password: password
  data:
    r2dbc:
      repositories:
        enabled: true

fx:
  currencies: USD, EUR
  tasks:
    enabled: false

server:
  port: 8081
  shutdown: graceful

polygon-gateway:
  baseUrl: ${POLYGON_GATEWAY_BASE_URL:http://localhost:8080/}
